<?php
    session_start();
    unset($_SESSION["email"]);
    unset($_SESSION["id_cliente"]);
    unset($_SESSION["nome"]);
    unset($_SESSION["tipo"]);
    session_destroy();
    header("location:../index.php");
    exit();
?>